# Generated by Django 4.2.5 on 2024-02-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity_players', models.PositiveSmallIntegerField(unique=True, verbose_name='Количество игроков')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/maps_images')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(verbose_name='Победа')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='PoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='VetoGameModeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='veto_game_info', to='games.gamemode', verbose_name='Режим игры')),
                ('veto', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='veto_game_info', to='games.veto', verbose_name='Вето')),
            ],
        ),
        migrations.CreateModel(
            name='PoolMapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.map', verbose_name='Карта')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.pool', verbose_name='Пул')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_group',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='pool', to='games.poolgroup', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='PlayerStatisticInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0, verbose_name='Количество убийств')),
                ('assists', models.IntegerField(default=0, verbose_name='Количество помощи')),
                ('deaths', models.IntegerField(default=0, verbose_name='Количество смертей')),
                ('headshots_count', models.IntegerField(default=0, verbose_name='Количество убийств в голову')),
                ('kr_ratio', models.FloatField(default=0, verbose_name='K/R')),
                ('mvp', models.PositiveSmallIntegerField(default=0, verbose_name='MVP')),
                ('triple_kills', models.PositiveSmallIntegerField(default=0, verbose_name='Количество тройных убийств')),
                ('quadro_kills', models.PositiveSmallIntegerField(default=0, verbose_name='Количество четверных убийств')),
                ('five_kills', models.PositiveSmallIntegerField(default=0, verbose_name='Количество пятерных убийств')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра')),
            ],
        ),
    ]
