# Generated by Django 4.2.5 on 2023-10-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatisticingame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playermatchinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to='games.game', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='playermatchinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='match',
            name='game1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='game2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='game3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра 3'),
        ),
        migrations.AddField(
            model_name='match',
            name='game4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра 4'),
        ),
        migrations.AddField(
            model_name='match',
            name='game5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Игра 5'),
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.gamemode', verbose_name='Режим BEST_OF'),
        ),
        migrations.AddField(
            model_name='match',
            name='veto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.veto', verbose_name='Вето'),
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.map', verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.gamestatus', verbose_name='Статус'),
        ),
    ]
