# Generated by Django 4.2.5 on 2023-09-23 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatisticingame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.gametype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lobby.lobby', verbose_name='Лобби'),
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.gamemap', verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.gamestatus', verbose_name='Статус'),
        ),
    ]
