# Generated by Django 4.2.5 on 2024-02-06 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatisticingame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to='games.game', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamemode', verbose_name='Режим BEST_OF'),
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gametype', verbose_name='Тип игры'),
        ),
        migrations.AddField(
            model_name='match',
            name='veto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.veto', verbose_name='Вето'),
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.map', verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.gamestatus', verbose_name='Статус'),
        ),
    ]
