# Generated by Django 4.2.5 on 2023-10-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game1', to='games.game', verbose_name='Игра 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2', to='games.game', verbose_name='Игра 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game3', to='games.game', verbose_name='Игра 3'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game4', to='games.game', verbose_name='Игра 4'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game5', to='games.game', verbose_name='Игра 5'),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamemode', verbose_name='Режим BEST_OF'),
        ),
        migrations.AlterField(
            model_name='match',
            name='veto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.veto', verbose_name='Вето'),
        ),
    ]
