# Generated by Django 5.0.1 on 2024-02-06 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bet',
            field=models.IntegerField(default=0, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.ForeignKey(default=0, max_length=255, on_delete=django.db.models.deletion.PROTECT, to='games.map', verbose_name='Карта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='max_lvl_enter',
            field=models.IntegerField(null=True, verbose_name='Максимальный уровень для входа'),
        ),
        migrations.AddField(
            model_name='match',
            name='min_lvl_enter',
            field=models.IntegerField(null=True, verbose_name='Минимальный уровень для входа'),
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.pool', verbose_name='Пул'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.BooleanField(verbose_name='Команда')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='games.match', verbose_name='Матч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
