# Generated by Django 4.2.5 on 2023-09-28 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lobby',
        ),
        migrations.AlterField(
            model_name='game',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.gamemap', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='games.gamestatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to='games.game', verbose_name='Матч'),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_info', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
    ]
