# Generated by Django 4.2.5 on 2023-10-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_match_game1_alter_match_game2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
    ]
