# Generated by Django 4.2.5 on 2023-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamemode_remove_game_game_type_remove_game_lobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
    ]
