# Generated by Django 4.2.5 on 2023-09-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_veto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetoGameModeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='veto_game_info', to='games.gamemode', verbose_name='Режим игры')),
                ('veto', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='veto_game_info', to='games.veto', verbose_name='Вето')),
            ],
        ),
    ]
