# Generated by Django 4.2.5 on 2023-09-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_vetogamemodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='quantity_games',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Количество игр'),
            preserve_default=False,
        ),
    ]
