# Generated by Django 4.2.5 on 2023-10-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='min_lvl_enter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_lvl_enter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='password_lobby',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
