# Generated by Django 5.0.1 on 2024-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='map',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='max_lvl_enter',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='min_lvl_enter',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='playerlobby',
            name='in_lobby',
        ),
        migrations.RemoveField(
            model_name='playerlobby',
            name='team_id',
        ),
    ]
