# Generated by Django 4.2.5 on 2024-01-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_playerlobby_time_enter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='veto',
        ),
    ]
